language: php

php:
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql

before_script:
  - composer install
  - wget https://scrutinizer-ci.com/ocular.phar
  - mysql -e "create database IF NOT EXISTS zfc_user;" -uroot

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs -n --standard=PSR2 ./module/ZfcUser/src/ ./module/ZfcUser/test/

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - php vendor/bin/php-coveralls
